name: Auto Approve Release PRs

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    name: Auto Approve Release PRs
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/') && github.actor == 'github-actions[bot]'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
