name: Deploy Build (GitHub Packages)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (X.Y.Z)"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ github.event.inputs.version }}
          path: dist/

      - name: Publish to GitHub Packages (Python)
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}
          OWNER: cblack2008
        run: |
          python -m pip install -U pip twine
          twine upload --repository-url https://pypi.pkg.github.com/${OWNER} dist/*
