name: Prepare Release (Build + Tag + Next Dev)

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: "Version bump"
        default: patch
        options: [patch, minor, major, custom]
      custom_version:
        description: "If custom selected, enter X.Y.Z"
        required: false
      base_ref:
        description: "Base branch/ref to create the release from (defaults to the branch this workflow runs on)"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      version: ${{ steps.ver.outputs.new }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # If base_ref provided, check out that; otherwise the ref that triggered the workflow
          ref: ${{ inputs.base_ref != '' && inputs.base_ref || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Compute next release version
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          echo "Current HEAD ref: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current HEAD sha: $(git rev-parse HEAD)"
          BUMP="${{ github.event.inputs.bump }}"
          CUSTOM="${{ github.event.inputs.custom_version }}"
          FILE=src/event_bridge_log_shared/_version.py
          CURR=$(python -c "import re;print(re.search(r'__version__\\s*=\\s*\"([^\"]+)\"', open(\"$FILE\").read()).group(1))")
          echo "Input bump: '$BUMP' ; custom_version: '${CUSTOM:-}' ; current: $CURR"
          if [[ -n "${CUSTOM:-}" ]]; then
            NEW="$CUSTOM"
          else
            IFS=. read -r MA MI PA <<<"$CURR"
            case "$BUMP" in
              major) NEW="$((MA+1)).0.0" ;;
              minor) NEW="$MA.$((MI+1)).0" ;;
              patch) NEW="$MA.$MI.$((PA+1))" ;;
              *) echo "Invalid bump: $BUMP"; exit 1 ;;
            esac
          fi
          echo "version $NEW"
          echo "new=$NEW" >> "$GITHUB_OUTPUT"

      - name: Guard existing release branch
        shell: bash
        run: |
          set -euo pipefail
          NEW="${{ steps.ver.outputs.new }}"
          if git ls-remote --exit-code --heads origin "refs/heads/release/v$NEW" >/dev/null 2>&1; then
            echo "release/v$NEW already exists. Merge/close it or choose another version." >&2
            exit 1
          fi

      - name: Create release branch and commit
        shell: bash
        run: |
          set -euo pipefail
          NEW="${{ steps.ver.outputs.new }}"
          BR="release/v${NEW}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BR"
          FILE=src/event_bridge_log_shared/_version.py
          echo "Applying version $NEW to $FILE on branch $BR"
          python -m pip install -U hatch
          hatch version "$NEW"
          # Verify hatch actually updated the file; if not, fall back to sed replacement (portable POSIX class)
          AFTER=$(python -c "import re;print(re.search(r'__version__\\s*=\\s*\"([^\"]+)\"', open(\"$FILE\").read()).group(1))")
          if [ "$AFTER" != "$NEW" ]; then
            echo "Hatch did not update version (got $AFTER). Applying sed fallback..."
            sed -i.bak -E "s/^(__version__)[[:space:]]*=[[:space:]]*\"[^\"]+\"/\\1 = \"${NEW}\"/" "$FILE"
            rm -f "$FILE.bak"
            AFTER=$(python -c "import re;print(re.search(r'__version__\\s*=\\s*\"([^\"]+)\"', open(\"$FILE\").read()).group(1))")
          fi
          echo "Old version found: $(git show :$FILE | sed -n '1,1p' 2>/dev/null || true)"
          echo "File now has version: $AFTER"
          if [ "$AFTER" != "$NEW" ]; then
            echo "Version in $FILE still not $NEW; aborting." >&2
            exit 1
          fi
          echo "Git status before add:" && git status --porcelain
          echo "Diff for file before commit:" && git diff -- "$FILE" || true
          git add "$FILE"
          git commit -m "chore(release): v${NEW}"
          git push -u origin "$BR"

      - name: Verify branch contains bumped version (pre-PR)
        shell: bash
        run: |
          set -euo pipefail
          NEW="${{ steps.ver.outputs.new }}"
          FILE=src/event_bridge_log_shared/_version.py
          BR="release/v${NEW}"
          git fetch origin "$BR" --force
          REMOTE=$(git show "origin/$BR:$FILE" | python -c "import re,sys;print(re.search(r'__version__\\s*=\\s*\"([^\"]+)\"', sys.stdin.read()).group(1))")
          echo "Remote $FILE on $BR: $REMOTE"
          test "$REMOTE" = "$NEW"

      - name: Build distributions
        run: |
          python -m pip install -U pip build hatch
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ steps.ver.outputs.new }}
          path: dist/

      - name: Open Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/v${{ steps.ver.outputs.new }}
          base: main
          title: "chore(release): v${{ steps.ver.outputs.new }}"
          body: |
            Prepare release v${{ steps.ver.outputs.new }}.

            A built artifact has been uploaded as `dist-${{ steps.ver.outputs.new }}`.
          labels: release
          reset-branch: false

      - name: Verify branch still contains bumped version (post-PR)
        shell: bash
        run: |
          set -euo pipefail
          NEW="${{ steps.ver.outputs.new }}"
          FILE=src/event_bridge_log_shared/_version.py
          BR="release/v${NEW}"
          git fetch origin "$BR" --force
          REMOTE=$(git show "origin/$BR:$FILE" | python -c "import re,sys;print(re.search(r'__version__\\s*=\\s*\"([^\"]+)\"', sys.stdin.read()).group(1))")
          echo "Remote $FILE on $BR (after PR step): $REMOTE"
          test "$REMOTE" = "$NEW"

      - name: Enable auto-merge
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
