name: Tag on Release PR Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show key fields
        run: |
          echo "merged: ${{ github.event.pull_request.merged }}"
          echo "base.ref: ${{ github.event.pull_request.base.ref }}"
          echo "head.ref: ${{ github.event.pull_request.head.ref }}"
  tag_release:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'release/v') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release branch merged to main; tagging…"
      - name: Checkout merge commit (with fallback)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}

      - name: Derive tag from branch
        id: tag
        shell: bash
        run: |
          BR='${{ github.event.pull_request.head.ref }}'    # e.g. release/v1.0.9
          TAG="${BR#release/}"                               # -> v1.0.9
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create tag
        uses: anothrNick/github-tag-action@v1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.tag.outputs.tag }}
          WITH_V: false
          DRY_RUN: false
