name: Tag on Release PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'release/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create tag at merge commit
        env:
          V: ${{ github.event.pull_request.head.ref }}
          SHA: ${{ github.event.pull_request.merge_commit_sha }}
        run: |
          set -euo pipefail
          TAG="${V#release/}"
          echo "Creating tag ${TAG} at ${SHA}"
          git fetch --tags --force
          if git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null; then
            echo "Tag ${TAG} already exists, skipping"
            exit 0
          fi
          git tag -a "${TAG}" -m "release ${TAG}" "${SHA}"
          git push origin "${TAG}"
